### ISSUE TITLE
push built docker containers to docker hub for tagged releases 

### ISSUE THREAD

**Issue by Enmk** [Appscrunch/Multy-ETH-node-service#4]
Once the commit is in the branch `vX.Y` and has tag `vX.Y.Z`, build and push a docker image with a tag `X.Y.Z` to docker hub.

Please also see: https://github.com/Multy-io/Multy-BTC-node-service/issues/7

**Comment by abitrolly** [comment]
Travis ignores branch name if tag is used, so every tag will get pushed. Also right now there is the only tag `release_1,2` without `v` so I don't strip it.

https://github.com/Multy-io/Multy-ETH-node-service/tags

**Comment by abitrolly** [comment]
@Enmk can you, plz. make any tag in this repo?
